# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

env:
 - CXX14FLAGS=-O3 -march=native -mtune=native -fPIC CXX14=g++

cache: packages

r:
  - 3.5
  - 3.6
  - devel
  
os:
  - linux
  - osx
  
matrix:
  exclude:
  allow_failures:
  - r: devel
    os: linux
  - r: devel
    os: osx
  - r: 3.5
    os: osx
  - r: 3.6
    os: linux
  - r: 3.6
    os: osx
    

addons:
  apt:
    packages:
      - libudunits2-dev
      - python
      - python-sympy

r_github_packages:
  - jimhester/covr
  - nlmixrdevelopment/dparser-R
  - nlmixrdevelopment/RxODE
  
script: 
  - |
    mkdir ~/.R
    echo > ~/.R/Makevars
    echo CXX14FLAGS=-O3 -march=native -mtune=native -fPIC >> ~/.R/Makevars
    echo CXX14=g++ >> ~/.R/Makevars
    echo CXX14STD=-std=c++1y >> ~/.R/Makevars
    R CMD build .
    travis_wait 40 R CMD check nlmixr*tar.gz
    
after_failure:
- find *Rcheck -name '*.fail' -print -exec cat '{}' \;

after_success:
  - travis_wait 20 Rscript -e 'covr::codecov(line_exclusions=c("R/RxODE-win-setup.R", "src/errmsg.f", "src/rprint.c"))'
